server:
  port: 8081

spring:

  datasource:
    url: 
    username: 
    password: 

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        default_schema: profile

  liquibase:
    enabled: true
    default-schema: profile
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 

aws:

  cognito:

    region: 

    user-pool-id: 

    client-id: 

    domain:

    issuer-uri: 

    openid-configuration-uri:

    jwks-uri: 
