server:
  port: 8081

spring:

  datasource:
    url:{DATASOURCEURL} 
    username: {DATASOURCE-USERNAME}
    password: {DATASOURCE-PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        default_schema: profile

  liquibase:
    enabled: true
    default-schema: profile
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: {OAUTH-URI}

aws:

  cognito:

    region:{aws-region} 

    user-pool-id:{aws-user-pool-id} 

    client-id: {aws-client-id}

    domain: {aws-domain}

    issuer-uri: {aws-issuer-uri}

    openid-configuration-uri: {aws-openid-uri}

    jwks-uri: {aws-jwks-uri}
